### PR TITLE
Korean support for DiscordSRV

### PR DESCRIPTION
**Pull request by Alex4386**
Just as what I mentioned in the title, This is a korean yml for DiscordSRV

(Still needs to translate the message.yml but I hope it can help DiscordSRV to support various languages)

### CODE REVIEW

**Comment by Alex4386** [comment]
Feel free about requesting me a further localization if required.

**Comment by Scarsz** [comment]
Be sure to translate the messages file & modify LangUtil

**Comment by Alex4386** [comment]
Will translate LangUtil when I got home. Thanks for the feedback

**Comment by Alex4386** [comment]
Seems to be done. Checking for typing mistakes now.

**Comment by Alex4386** [comment]
Checked typing mistakes. It is now ready to go

**Pull request merged**
