### PR TITLE
Develop: Can you add a custom message for /discord link ?

### PR DESCRIPTION
**Pull request by Killdore21**
Because if you want custom language support, it would be nice to have a custom /discord link-message ...

- Killdore :)

### CODE REVIEW

**Comment by Scarsz** [comment]
1. This is a pull request. Pull requests are used to submit code, not ask for features.

2. I already told you, no.

**Comment by Killdore21** [comment]
1. Sorry then.

2. You just said I could put it here. Sorry if I didn't understand it then ...

**Comment by Scarsz** [comment]
No, I said you could submit a *full* translation of DiscordSRV for whatever language you want so bad, as the instructions I gave you said.

**Comment by Killdore21** [comment]
I don't want it so badly. I just asked ... Sorry then, for not understanding what you mean :/

**Pull request closed without merging**
