### PR TITLE
Dutch translations added

### PR DESCRIPTION
**Pull request by tomkeuper**

### CODE REVIEW

**Comment by Androkai** [comment]
These lines can also be translated:

__config.yml__:
- 155 (depends on lines 100-101 in messages.yml)
- 234

__messages.yml__:
- 92
- 100-101
- 112-114
- 138
- 165-168
- 173
- 179-180
- 193
- 206-208

**Comment by Scarsz** [comment]
Also don't tag yourself in the `*.yml` files as a reference for help

**Comment by Androkai** [comment]
No further complaint on my part.

**Comment by tomkeuper** [comment]
I changed the "gejoined" in to "verbonden"
I believe it ready now.

**Comment by Androkai** [comment]
@Scarsz Final review + decision please

**Comment by Scarsz** [comment]
Names of roles should probably be translated as well i.e. https://github.com/Scarsz/DiscordSRV/pull/299/files#diff-5d41ab3a36f24f1a9ec2dbabfe045c5bR128

**Comment by tomkeuper** [comment]
i can look but we dont really have translations for those words in dutch. but i will google it tommorow

**Comment by tomkeuper** [comment]
done

**Comment by Greeem** [comment]
everything?

**Comment by Androkai** [comment]
I took the liberty of merging them.

@tomkeuper Thank you for your efforts.

**Comment by tomkeuper** [comment]
No problemo

**Pull request merged**
