### PR TITLE
Create hu language

### PR DESCRIPTION
**Pull request by montlikadani**
IMPORTANT!
**Encoding: ANSI**
It is necessary to display the accents in the chat.

### CODE REVIEW

**Comment by Scarsz** [comment]
DiscordSRV uses UTF-8 encoding. Also, you have only translated one of the three files required for this translation to be functional. Please read https://github.com/Scarsz/DiscordSRV/blob/master/CONTRIBUTING.md#translating.

**Comment by montlikadani** [comment]
All right, then pull this Pull Request and then compile it and then let me know.

**Comment by Scarsz** [comment]
...no. You have not done the translation properly.

**Comment by montlikadani** [comment]
But I've already started translating LangUtils.java.

**Comment by BillyGalbreath** [comment]
@montlikadani If your server isn't reading UTF-8 yml files properly, then you need to properly setup your Java environment to use UTF-8 encoding. Those accents are not dependent of any encoding like you think.

**Comment by montlikadani** [comment]
@BillyGalbreath 
But accented letters, for example: 'é' with ANSI encoding can be displayed in chat, this is written elsewhere.

**Comment by BillyGalbreath** [comment]
@montlikadani Change your server startup script to include the UTF-8 encoding...

`java -Dfile.encoding=UTF8 -jar spigot.jar`

ANSI is not a requirement.. Not going to say it again.

**Comment by montlikadani** [comment]
@BillyGalbreath 
It's okay, I guess this ANSI encoding.

**Pull request closed without merging**
