### PR TITLE
Create hu.yml config file

### PR DESCRIPTION
**Pull request by montlikadani**
There is more?

### CODE REVIEW

**Comment by BillyGalbreath** [comment]
Why is your single PR spread across multiple PRs?

**Comment by montlikadani** [comment]
@BillyGalbreath 
Because I do not know how to do it.

**Comment by BillyGalbreath** [comment]
It's quite simple. Make all your edits, then commit and push to github then make PR...

Here is a quick example on what your 3 PRs look like in a single commit: https://github.com/BillyGalbreath/DiscordSRV/commit/666303df65825c6385062cf800c22f10c470d2ed

**Comment by montlikadani** [comment]
@BillyGalbreath 
Yes, I just do not have permission.

**Comment by BillyGalbreath** [comment]
You dont have permission to make a single commit to your own fork?

**Comment by montlikadani** [comment]
How should it be? Because I have no function.

**Pull request closed without merging**
