### PR TITLE
Replaced while + sleep with blocking operation

### PR DESCRIPTION
**Pull request by Almighty-Alpaca**

### CODE REVIEW

**Comment by Almighty-Alpaca** [comment]
why :sob:

**Comment by Scarsz** [comment]
I specifically don't want to use `JDABuilder#buildBlocking` & I already changed the JDA#shutdown call myself in a later commit

**Comment by Almighty-Alpaca** [comment]
`JDABuilder#buildBlocking()` is made for exactly that purpose

**Comment by Scarsz** [comment]
Okay, but notice me doing it with buildAsync gives me the JDA object while it's being built whereas buildBlocking doesn't give it until after it's completely loaded. If the debug handler tries to do a report for DiscordSRV and JDA isn't built yet, not only will it error on multiple things but it will be unable to debug JDA building issues.

**Pull request closed without merging**
