### PR TITLE
French translations

### PR DESCRIPTION
**Pull request by Niasio**

### CODE REVIEW

**Comment by Scarsz** [comment]
What?

**Comment by Niasio** [comment]
It's the first french translation

**Comment by Scarsz** [comment]
This translation is... far from complete. The only things that've been changed are config value strings. There's much, much more to translate than that.

**Comment by Niasio** [comment]
Ow .. Yes sure

**Comment by Scarsz** [comment]
Closing due to no activity

**Comment by Niasio** [comment]
It's in work

**Comment by Scarsz** [comment]
It doesn't take almost a month to translate three files.

**Pull request closed without merging**
